### ISSUE TITLE
Geoglam - Apr 2021 release 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/geoglam-nm#100]
- [x] Feedback from Geoglam team - pending 
- [x] update help page https://github.com/TerriaJS/RaPPMap/issues/113
- [x] Legends issues - https://github.com/TerriaJS/RaPPMap/issues/109
- [x] Catalog converter - Open/close state of items in workbench - TerriaJS/catalog-converter#22 - Merged 
- [x] Support adding items to workbench on load - TerriaJS/catalog-converter#26
 - [x] catalog-converter PR for generating random IDs - TerriaJS/catalog-converter#28 - merged
 - [x] catalog-converter PR for populating workbench with IDs of items with isEnabled: true - TerriaJS/catalog-converter#29 - merged

**Comment by AnaBelgun** [comment]
Migration from v7 to v8 https://geo-rapp.test.saas.terria.io/ 

- [x] WPS - https://github.com/TerriaJS/terriajs/issues/5150

- [x] dates not displaying the entire date, just the year - https://github.com/TerriaJS/RaPPMap/issues/104
- [x] search by location doesn't work - https://github.com/TerriaJS/RaPPMap/issues/106
- [x] Bing base maps don't work - https://github.com/TerriaJS/RaPPMap/issues/107
- [x] feature info template doesn't work - https://github.com/TerriaJS/RaPPMap/issues/108
- [x] legends missing - https://github.com/TerriaJS/RaPPMap/issues/109

**Comment by nf-s** [comment]
All done!
