### ISSUE TITLE
Geoglam - Sep - 30 Nov 2020 migration to MobX 

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/geoglam-nm#87]
- [x] Needs WMTS in V8 - https://github.com/TerriaJS/terriajs/issues/4218
- [x] Related - https://github.com/TerriaJS/terriajs/pull/4406
- [x] MobX-ing - 

Checklist:
- [ ] WMS
- [ ] WMTS
- [ ] WPS

TODOs:

- [x] Initial port to get the map running on v8 - #95
- [x] Do a saas deployment
- [ ] Set default base map
- [ ] Fix feature info templates - some of them use css classes to do funky things, figure out how to replicate in v8
- [ ] Console errors when interacting with explorer
- [ ] Quite a few catalog items displays "experiencing issues" in preview
- [ ] WPS forms not displaying human friendly labels for input fields
- [ ] Preview text not shown on tab switch
- [ ] Implement downtime notice

**Comment by AnaBelgun** [comment]
Catalogue conversion: https://github.com/TerriaJS/RaPPMap/issues/92

**Comment by AnaBelgun** [comment]
- when in dev env, to test adding a new data and running a process using "existing polygon" - @juan-guerschman

**Comment by na9da** [comment]
### Progress

- [x] ~To add items on workbench on app start - https://github.com/TerriaJS/terriajs/pull/4997 - needs discussion~
- [x] Fixes group item preview errors - https://github.com/TerriaJS/terriajs/pull/5001
- [x] Hides info sections with empty content in preview - https://github.com/TerriaJS/terriajs/pull/4999
- [x] Various WPS fixes - https://github.com/TerriaJS/terriajs/pull/5003
- [x] Tab switching errors - https://github.com/TerriaJS/terriajs/pull/5000 - needs discussion 
- [ ] Catalog converter - Open/close state of items in workbench -  https://github.com/TerriaJS/catalog-converter/pull/22
- [x] Catalog converter - convert tablestyles (for wps response) - https://github.com/TerriaJS/catalog-converter/pull/20
- [x] Fix mobx warnings when loading geojson catalog item - https://github.com/TerriaJS/terriajs/pull/5005
- [ ] Help Page (will decide wether/what to port once Juan and others have a look at the new Help page)
- [x] Logos in disclaimer
- [x] Downtime notice in disclaimer
- [ ] Support adding items to workbench on load - https://github.com/TerriaJS/catalog-converter/issues/26
   - [ ] catalog-converter PR for generating random IDs - https://github.com/TerriaJS/catalog-converter/pull/28
   - [ ] catalog-converter PR for populating `workbench` with IDs of items with `isEnabled: true` - https://github.com/TerriaJS/catalog-converter/pull/29
- [ ] ...

**Comment by na9da** [comment]
For deploying an 80% geoglam we need one more PR to be merged (TerriaJS/catalog-converter#20). The rest are not essential!

**Comment by nf-s** [comment]
Great thanks @na9da !
Does that catalog-converter PR need to be merged and published for use in Terrace? Or just for converting catalog offline

**Comment by AnaBelgun** [comment]
Geoglam released on v8 for testing: https://geo-rapp.test.saas.terria.io/ 
Sent to Ag & Food team to test on 3/12/2020. Pending results.

**Comment by AnaBelgun** [comment]
This ticket is superseded by monthly release ticket/s https://github.com/TerriaJS/RaPPMap/issues/100
